apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sock-shop-orders
  labels:
    release: prometheus-operator
  namespace: monitoring
spec:
  jobLabel: orders-metrics
  selector:
    matchLabels:
      name: orders
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - targetPort: 80
    path: /metrics