{
 "title": "Sock-Shop Performance",
 "description": "Monitor and visualise Sock Shop application metrics metrics interleaved with chaos events and chaos exporter metrics from LitmusChaos. ",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Chaos Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Orders Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Orders QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"orders\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"orders\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    },
    {
     "expr": "heptio_eventrouter_normal_total{reason=\"ChaosInject\",involved_object_name=\"orders-pod-memory-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} - on () (heptio_eventrouter_normal_total{reason=\"ChaosEngineCompleted\",involved_object_name=\"orders-pod-memory-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} OR on() vector(0))",
     "legendFormat": "orders-pod-memory-hog"
    },
    {
     "expr": "heptio_eventrouter_normal_total{reason=\"ChaosInject\",involved_object_name=\"orders-node-memory-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} - on () (heptio_eventrouter_normal_total{reason=\"ChaosEngineCompleted\",involved_object_name=\"orders-node-memory-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} OR on() vector(0))",
     "legendFormat": "orders-node-memory-hog"
    }
   ]
  },
  {
   "title": "Orders latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{job=\"orders\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{job=\"orders\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{job=\"orders\"}[1m])) / sum(rate(request_duration_seconds_count{job=\"orders\"}[1m]))",
     "legendFormat": "Mean"
    },
    {
     "expr": "heptio_eventrouter_normal_total{reason=\"ChaosInject\",involved_object_name=\"orders-pod-memory-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} - on () (heptio_eventrouter_normal_total{reason=\"ChaosEngineCompleted\",involved_object_name=\"orders-pod-memory-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} OR on() vector(0))",
     "legendFormat": "orders-pod-memory-hog"
    },
    {
     "expr": "heptio_eventrouter_normal_total{reason=\"ChaosInject\",involved_object_name=\"orders-node-memory-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} - on () (heptio_eventrouter_normal_total{reason=\"ChaosEngineCompleted\",involved_object_name=\"orders-node-memory-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} OR on() vector(0))",
     "legendFormat": "orders-node-memory-hog"
    }
   ]
  },
  {
   "title": "Catalogue Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Catalogue QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"catalogue\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"catalogue\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    },
    {
     "expr": "heptio_eventrouter_normal_total{reason=\"ChaosInject\",involved_object_name=\"catalogue-pod-cpu-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} - on () (heptio_eventrouter_normal_total{reason=\"ChaosEngineCompleted\",involved_object_name=\"catalogue-pod-cpu-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} OR on() vector(0))",
     "legendFormat": "catalogue-pod-cpu-hog"
    },
    {
     "expr": "heptio_eventrouter_normal_total{reason=\"ChaosInject\",involved_object_name=\"catalogue-node-cpu-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} - on () (heptio_eventrouter_normal_total{reason=\"ChaosEngineCompleted\",involved_object_name=\"catalogue-node-cpu-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} OR on() vector(0))",
     "legendFormat": "catalogue-node-cpu-hog"
    }
   ]
  },
  {
   "title": "Catalogue latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{job=\"catalogue\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{job=\"catalogue\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{job=\"catalogue\"}[1m])) / sum(rate(request_duration_seconds_count{job=\"catalogue\"}[1m]))",
     "legendFormat": "Mean"
    },
    {
     "expr": "heptio_eventrouter_normal_total{reason=\"ChaosInject\",involved_object_name=\"catalogue-pod-cpu-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} - on () (heptio_eventrouter_normal_total{reason=\"ChaosEngineCompleted\",involved_object_name=\"catalogue-pod-cpu-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} OR on() vector(0))",
     "legendFormat": "catalogue-pod-cpu-hog"
    },
    {
     "expr": "heptio_eventrouter_normal_total{reason=\"ChaosInject\",involved_object_name=\"catalogue-node-cpu-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} - on () (heptio_eventrouter_normal_total{reason=\"ChaosEngineCompleted\",involved_object_name=\"catalogue-node-cpu-hog\", involved_object_namespace=\"litmus\", involved_object_kind=\"ChaosEngine\"} OR on() vector(0))",
     "legendFormat": "catalogue-node-cpu-hog"
    }
   ]
  },
  {
   "title": "Payement Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Payment QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"payment\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"payment\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Payment latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{job=\"payment\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{job=\"payment\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{job=\"payment\"}[1m])) / sum(rate(request_duration_seconds_count{job=\"payment\"}[1m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Shipping Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shipping QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"shipping\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"shipping\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Shipping latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{job=\"shipping\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{job=\"shipping\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{job=\"shipping\"}[1m])) / sum(rate(request_duration_seconds_count{job=\"shipping\"}[1m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "User Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "User QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"user\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"user\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "User latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{job=\"user\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{job=\"user\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{job=\"user\"}[1m])) / sum(rate(request_duration_seconds_count{job=\"user\"}[1m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Frontend Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Frontend QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"front-end\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"front-end\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Frontend latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{job=\"front-end\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{job=\"front-end\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{job=\"front-end\"}[1m])) / sum(rate(request_duration_seconds_count{job=\"front-end\"}[1m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Cart Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cart QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"carts\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"carts\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Cart latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{job=\"carts\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{job=\"carts\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{job=\"carts\"}[1m])) / sum(rate(request_duration_seconds_count{job=\"carts\"}[1m]))",
     "legendFormat": "Mean"
    }
   ]
  }
 ]
}