apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert-staging
  namespace: monitoring
spec:
  secretName: grafana-cert-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: grafana.anynamefits.ru
  dnsNames:
  - grafana.anynamefits.ru
  
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert-production
  namespace: monitoring
spec:
  secretName: grafana-cert-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: grafana.anynamefits.ru
  dnsNames:
  - grafana.anynamefits.ru
