apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop
spec:
  destination:
    name: ''
    namespace: sock-shop
    server: 'https://kubernetes.default.svc'
  source:
    path: sock-shop
    repoURL: 'git@github.com:anmcqueen/kubernetes-final-work.git'
    targetRevision: main
    directory:
      recurse: true
  sources: []
  project: default
