apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop-helm
spec:
  destination:
    name: ''
    namespace: sock-shop
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-charts/sock-shop
    repoURL: 'git@github.com:anmcqueen/kubernetes-final-work.git'
    targetRevision: dev # TODO перейти на main
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated: null

