apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert-staging
  namespace: argocd
spec:
  secretName: argocd-cert-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: argocd.anynamefits.ru
  dnsNames:
  - argocd.anynamefits.ru