apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-cert-production
  namespace: vault
spec:
  secretName: vault-cert-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: vault.anynamefits.ru
  dnsNames:
  - vault.anynamefits.ru