---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    name: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catalogue
  template:
    metadata:
      labels:
        name: catalogue
      annotations:
      	{{- if .Values.istio.enabled }}
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      	{{- end }}
      	{{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-limits-cpu: 250m
        vault.hashicorp.com/role: "service"
        vault.hashicorp.com/agent-inject-secret-catalogue_user_pass: "secrets/sock-shop/catalogue_user"
        vault.hashicorp.com/agent-inject-template-catalogue_user_pass: |
          {{"{{ with secret \"secrets/sock-shop/catalogue_user\" -}}{{ .Data.password }}{{ end }}"}}
        vault.hashicorp.com/agent-inject-secret-catalogue_user_login: "secrets/sock-shop/catalogue_user"
        vault.hashicorp.com/agent-inject-template-catalogue_user_login: |
          {{"{{ with secret \"secrets/sock-shop/catalogue_user\" -}}{{ .Data.username }}{{ end }}"}}
      	{{- end }}
    spec:
      containers:
      - name: catalogue
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.catalogue.image.repo }}:{{ .Values.catalogue.image.tag }}
        command:
          - sh
        args:
        - '-c'
        - |
          export pass=$(cat /vault/secrets/catalogue_user_pass); 
          export login=$(cat /vault/secrets/catalogue_user_login); 
          echo $var;
          /app -port={{ .Values.catalogue.containerPort }} -DSN="$login:$pass@tcp(catalogue-db.{{ .Release.Namespace }}.svc.cluster.local:3306)/socksdb"
        {{- if .Values.zipkin.enabled }}
        env:
         - name: ZIPKIN
           value: http://{{ .Values.zipkin.url }}:9411/api/v1/spans
        {{- end }}
        resources:
{{ toYaml .Values.catalogue.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.catalogue.containerPort }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
{{- if lt (int .Values.carts.containerPort) 1024 }}
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
{{- end }}
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.catalogue.containerPort }}
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.catalogue.containerPort }}
          initialDelaySeconds: 180
          periodSeconds: 3
