apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-end-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
    {{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host }}
    {{- end }}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
  - secretName: {{ .Values.ingress.tlsSecretName }}
    {{- if .Values.ingress.host }}
    hosts:
    - {{ .Values.ingress.host }}
    {{- end }}
  {{- end }}
